#!/bin/sh
set -u

APP_DIR=${RIDDLE_APP_DIR:-/mnt/onboard/.adds/riddle-kobo}
KOBO_DIR=${RIDDLE_KOBO_DIR:-/usr/local/Kobo}
BIN="$APP_DIR/riddle"
LOG="$APP_DIR/riddle.log"
STATE="$APP_DIR/framebuffer.state"
LOCK_DIR="$APP_DIR/run.lock"
CHILD=
NICKEL_STOPPED=0

log() {
    printf '%s\n' "$*" >>"$LOG"
}

start_nickel() {
    if [ -x "$KOBO_DIR/hindenburg" ]; then
        "$KOBO_DIR/hindenburg" >>"$LOG" 2>&1 &
    fi
    LIBC_FATAL_STDERR_=1 "$KOBO_DIR/nickel" -platform kobo -skipFontLoad >>"$LOG" 2>&1 &
}

restore_framebuffer() {
    [ -s "$STATE" ] || return 1
    # State is generated by our own helper and contains exactly three integers.
    set -- $(cat "$STATE")
    [ "$#" -eq 3 ] || return 1
    "$BIN" --kobo-restore-state "$1" "$2" "$3" >>"$LOG" 2>&1
}

cleanup() {
    trap - EXIT INT TERM HUP
    if [ -n "$CHILD" ] && kill -0 "$CHILD" 2>/dev/null; then
        kill -TERM "$CHILD" 2>/dev/null || true
        wait "$CHILD" 2>/dev/null || true
    fi
    if [ "$NICKEL_STOPPED" -eq 1 ]; then
        if restore_framebuffer; then
            log "riddle: framebuffer restored; restarting Nickel"
            start_nickel
        else
            log "riddle: FATAL framebuffer restore failed; Nickel left stopped (power-cycle or run restore-nickel.sh over SSH)"
        fi
    fi
    rm -f "$LOCK_DIR/pid"
    rmdir "$LOCK_DIR" 2>/dev/null || true
}

forward_signal() {
    [ -n "$CHILD" ] && kill -TERM "$CHILD" 2>/dev/null || true
}

trap cleanup EXIT
trap forward_signal INT TERM HUP

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "riddle: launch refused; another instance or stale lock exists"
    exit 3
fi
printf '%s\n' "$$" >"$LOCK_DIR/pid"

mkdir -p "$APP_DIR/data/memories"
chmod 755 "$BIN" "$APP_DIR/restore-nickel.sh" 2>/dev/null || true

# Capture exact bpp/grayscale/native rotation while Nickel is still healthy.
if ! "$BIN" --kobo-capture-state >"$STATE" 2>>"$LOG"; then
    log "riddle: cannot capture framebuffer state; refusing to stop Nickel"
    exit 4
fi

# Follow KOReader's proven lifecycle: terminate Nickel, own the framebuffer,
# restore its exact mode, then start a fresh Nickel so it redraws everything.
killall -TERM nickel hindenburg sickel 2>/dev/null || true
NICKEL_STOPPED=1
i=0
while pidof nickel >/dev/null 2>&1 && [ "$i" -lt 25 ]; do
    sleep 0.2
    i=$((i + 1))
done
if pidof nickel >/dev/null 2>&1; then
    killall -KILL nickel 2>/dev/null || true
fi
sleep 1

export RIDDLE_MEMORY_DIR="$APP_DIR/data/memories"
if [ -f "$APP_DIR/oracle.env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$APP_DIR/oracle.env"
    set +a
fi

printf '\n=== launch %s ===\n' "$(date)" >>"$LOG"
case "${RIDDLE_LAUNCH_MODE:-diary}" in
    mailbox) "$BIN" --mailbox >>"$LOG" 2>&1 & ;;
    diary) "$BIN" >>"$LOG" 2>&1 & ;;
    *)
        log "riddle: unknown launch mode: $RIDDLE_LAUNCH_MODE"
        exit 5
        ;;
esac
CHILD=$!
wait "$CHILD"
STATUS=$?
CHILD=
printf '=== exit %s status=%s ===\n' "$(date)" "$STATUS" >>"$LOG"
exit "$STATUS"
